CONTIKI_PROJECT = hello-world-sub
all: $(CONTIKI_PROJECT)

MAKE_MAC =  MAKE_MAC_CSMA
MAKE_ROUTING = MAKE_ROUTING_RPL_LITE
MODULES += os/services/shell

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
